//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganieva_Azaliya_006.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deliverydate { get; set; }
        public Nullable<int> IdPoint { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> CodeDelivery { get; set; }
        public Nullable<int> IdStatusOrder { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
