//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganieva_Azaliya_006.DBCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdProductCateg { get; set; }
        public Nullable<double> ActiveDiscount { get; set; }
        public Nullable<int> CountOnSclad { get; set; }
        public string Discription { get; set; }
        public string Photo { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
